split("\r\n")|map(split(","))|
   map({"ID":.[0],
        "name":.[1],
        "display_name":.[2],
        "type":.[3],
        "display_frame":.[4],
        "time_range":.[5],
        "time_delta":.[6],
        "display_min_value":.[7],
        "display_max_value":.[8]
})